# Generated by Django 3.1.1 on 2020-09-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the resume owner', max_length=200)),
                ('contact_email', models.EmailField(help_text='The email that will appear on the resume', max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
