# Generated by Django 3.1.1 on 2020-09-26 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_api', '0002_link_project_skill_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the image', max_length=200)),
                ('image', models.ImageField(help_text='Image for a resume', upload_to='resume_media/images/')),
                ('resume', models.ForeignKey(help_text='Resume the image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='resume_api.resume')),
            ],
        ),
    ]
