# Generated by Django 3.1.1 on 2020-09-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_api', '0003_resumeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(help_text='The location of the project, if applicable', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='location',
            field=models.CharField(help_text='The location of the work, if applicable', max_length=200, null=True),
        ),
    ]
